# This role is for local installation of houdini for a license server
- file:
    path: /opt/houdini_install_script
    state: directory
    mode: 0700
    owner: vagrant

- pip:
    name: beautifulsoup4

- copy:
    src: /vagrant/modules/node_centos/modules/houdini_install_script/
    dest: /opt/houdini_install_script/
    directory_mode: yes

- file:
    path: /opt/houdini_install_script/houdini_install.py
    mode: 0700
    owner: vagrant
  
# - shell: |
#     python /opt/houdini_install_script/houdini_install.py -u {{ sesi_username }} -p {{ sesi_password }} -i /opt/houdini
#   register: houdini_install_out
#   become: true

# temp alternate install for ubuntu
- name: copy installer from downloads
  copy:
    src: /vagrant/downloads/houdini-17.5.173-linux_x86_64_gcc6.3.tar
    dest: /var/tmp/
  become: true

- name: check if hserver file exists
  stat: 
    path: /opt/hfs17.5/bin/hserver
  register: hserver_check
  become: true

- name: Stop licensing server if already running / installed.  Please ignore any error if hserver not running.
  shell: |
    /opt/hfs17.5/bin/hserver -q
  ignore_errors: yes
  become: true
  when: hserver_check.stat.exists == true

- name: install houdini
  shell: |
    set -x
    sudo chmod 600 /var/tmp/houdini-17.5.173-linux_x86_64_gcc6.3.tar
    cd /var/tmp
    sudo mkdir houdini_installer
    sudo tar -xvf houdini-17.5.173-linux_x86_64_gcc6.3.tar -C houdini_installer --strip-components 1
    cd houdini_installer
    sudo ./houdini.install --auto-install --accept-EULA --install-houdini --install-license --no-local-licensing --install-hfs-symlink
  register: houdini_install_out
  become: true

- debug:
    msg:  "{{ houdini_install_out.stdout }}"

- name: setup licensing mode
  shell: |
    cd /opt/hfs17.5
    sudo sed -i '/licensingMode = sesinetd/s/^# //g' /opt/hfs17.5/houdini/Licensing.opt
    sudo cat /opt/hfs17.5/houdini/Licensing.opt
    /opt/hfs17.5/bin/hserver
  become: true