---
# tasks file for openvpn_package

- name: Add apt repo - ubuntu # https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present
  become: true

- name: Add apt repo - /etc/apt/sources.list.d/openvpn-aptrepo.list
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/release/2.4 xenial main
    filename: openvpn-aptrepo
    state: present
  become: true

- name: install latest open vpn package
  package:
    name:
    - openvpn
    update_cache: yes
  become: true