---
# tasks file for roles/aws-cli
- name: install the package, force upgrade
  pip: 
    name: pip
    extra_args: --upgrade
  become_user: deadlineuser
  become: true

- name: install the package, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade --user
  become_user: deadlineuser
  become: true