---
#tasks file for roles/aws-cli
- name: install the package, force upgrade
  pip: 
    name: pip
    extra_args: --upgrade
  become: true

- name: install the package, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade --user
  become_user: vagrant
  become: true

- name: install the package, force upgrade
  apt: 
    name: python-boto
  become: true

- name: install the package, force upgrade
  pip: 
    name: boto3
  become: true

- name: Case insensitive password string match
  expect:
    command: aws configure
    responses:
      .*Access Key ID \[.*\]: "{{ aws_access_key }}"
      .*Secret Access Key \[.*\]: "{{ aws_secret_key }}"
      .*region name \[.*\]: "{{ aws_region }}"
      .*output format \[.*\]: json
    #echo: yes
  become_user: vagrant
  # you don't want to show passwords in your logs
  no_log: true