---
#tasks file for roles/aws-cli
- name: install the package, force upgrade
  pip: 
    name: pip
    extra_args: --upgrade
  become: true

- name: install the package for root, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade
  become_user: root

- name: install the package for user, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade --user
  #become_user: vagrant
  become_user: "{{ variable_user }}"
  become: true

- name: install python-boto package
  package:
    name: python-boto
  become: true

- name: install pip boto3
  pip:
    name: boto3
  become: true

- name: Case insensitive password string match for aws configure
  expect:
    command: /home/{{ variable_user }}/.local/bin/aws configure
    responses:
      .*Access Key ID \[.*\]: "{{ aws_access_key }}"
      .*Secret Access Key \[.*\]: "{{ aws_secret_key }}"
      .*region name \[.*\]: "{{ aws_region }}"
      .*output format \[.*\]: json
  become_user: "{{ variable_user }}"
  # you don't want to show passwords in your logs
  no_log: true