---
# tasks file for roles/terraform
- name: Ansible create file if it doesn't exist example
  file:
    path: "/vagrant/ansible-log.txt"
    state: touch
  become: yes

- name: Ensures dir exists
  file:
    path: /vagrant/downloads
    state: directory
  become: yes

- name: Download file
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    dest: /vagrant/downloads/terraform_0.11.11_linux_amd64.zip
  become: yes

- name: Ensures dir exists
  file:
    path: /vagrant/downloads/terraform_0.11.11_linux_amd64/
    state: directory
  become: yes

- name: Extract
  unarchive:
    src: /vagrant/downloads/terraform_0.11.11_linux_amd64.zip
    dest: /vagrant/downloads/terraform_0.11.11_linux_amd64/
  become: yes
  
- copy:
    src: /vagrant/downloads/terraform_0.11.11_linux_amd64/terraform
    dest: /usr/local/bin/terraform
    owner: vagrant
    group: vagrant
    mode: u=rx,g=rx,o=r
  become: yes
