---
# tasks file for roles/init-host
- name: change hostname to myserver
  hostname:
    name: "openfirehawkserver.{{ public_domain_prod }}"
- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost openfirehawkserver.{{ public_domain_prod }}"
    state: present

- name: Allow new lines from ansible shell output.  Logout or reboot for this to take effect.
  lineinfile:
    path: /etc/environment
    line: "ANSIBLE_STDOUT_CALLBACK=debug"
    create: yes

- name: define ssh config to push through a bastion host to get into private subnet.
  copy:
    dest: "/home/vagrant/.ssh/config"
    content: |
      host bastion
        Hostname bastion.{{ public_domain }}
        User centos 
        IdentityFile  ~/my_key_pair.pem

      Host 10.0.1.*
        IdentityFile  ~/my_key_pair.pem
        User centos
        ProxyCommand ssh -W %h:%p centos@bastion
    