---
- hosts: "{{ variable_host | default('firehawkgateway') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  become: true

  vars:
    my_password: "{{ user_deadlineuser_pw }}"
    no_extension: "{{ deadline_linux_installers_tar | splitext | first }}"
    basename: "{{ no_extension.split('/')[-1] }}"
    houdini_major_version: 18.0
    
  roles:
    - role: s3-bucket
    - {role: deadlinedb, tags: 'deadlinedb'}
    - role: deadlinercs

# This process archives secrets, and configures some settins.  they are copied to the repository, and encrypted by the vault id - keys/.vault-key
# Nothing stored in the secrets path should be unencrypted.

- hosts: "{{ variable_host | default('firehawkgateway') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  become: true
  become_user: root
  
  # secret 2 seems to occaisionally have issues and corrupts the shell output somehow.
  vars:
    ubl: true
    secrets:
      secret1:
        location: /opt/Thinkbox/certs/ca.crt
        target: "{{ secrets_archive }}/opt/Thinkbox/certs/ca.crt"
      secret2:
        location: /opt/Thinkbox/certs/Deadline10RemoteClient.pfx
        target: "{{ secrets_archive }}/opt/Thinkbox/certs/Deadline10RemoteClient.pfx"
      secret3:
        location: /opt/Thinkbox/certs/localhost.pfx
        target: "{{ secrets_archive }}/opt/Thinkbox/certs/localhost.pfx"
      secret4:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/ca.crt
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/ca.crt"
      secret5:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/Deadline10Client.pfx
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/Deadline10Client.pfx"
      secret6:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/localhost.pem
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/localhost.pem"
      secret7:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/mongo_client.pem
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/mongo_client.pem"
  
  pre_tasks:
  - name: store-secret
    with_items:
      - "{{ lookup('dict', secrets) }}"
    include_role:
      name: store-secret

  roles:
  - deadline-db-check # Check the db is functioning.
  - deadline-groups # Update groups for nodes.
  - deadline-ubl # Configure Usage Base Licesning.
  - deadline-db-check # Check the db is functioning after alterations.

- hosts: "{{ variable_host | default('firehawkgateway') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  become: true
  
  tasks:
  - name: reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection