---
- hosts: ansible_control
  become: true

  vars:
    my_password: "{{ user_deadlineuser_pw }}"
    no_extension: "{{ deadline_linux_installers_tar | splitext | first }}"
    basename: "{{ no_extension.split('/')[-1] }}"
    
  roles:
    - {role: 'newuser', tags: 'newuser'}
    - {role: deadlinedb, tags: 'deadlinedb'}
    - role: deadlinercs

# This process archives secrets.  they are copied to the repository, and encrypted by the vault id - keys/.vault-key
# Nothing stored in the secrets path should be unencrypted.

- hosts: ansible_control
  become: true
  remote_user: deadlineuser
  become_user: root
  
  # secret 2 seems to occaisionally have issues and corrupts the shell output somehow.
  vars:
    secrets:
      secret1:
        location: /opt/Thinkbox/certs/ca.crt
        target: "{{ secrets_archive }}/opt/Thinkbox/certs/ca.crt"
      secret2:
        location: /opt/Thinkbox/certs/Deadline10RemoteClient.pfx
        target: "{{ secrets_archive }}/opt/Thinkbox/certs/Deadline10RemoteClient.pfx"
      secret3:
        location: /opt/Thinkbox/certs/{{ openfirehawkserver_name }}.pfx
        target: "{{ secrets_archive }}/opt/Thinkbox/certs/{{ openfirehawkserver_name }}.pfx"
      secret4:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/ca.crt
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/ca.crt"
      secret5:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/Deadline10Client.pfx
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/Deadline10Client.pfx"
      secret6:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/{{ openfirehawkserver_name }}.pem
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/{{ openfirehawkserver_name }}.pem"
      secret7:
        location: /opt/Thinkbox/DeadlineDatabase10/certs/mongo_client.pem
        target: "{{ secrets_archive }}/opt/Thinkbox/DeadlineDatabase10/certs/mongo_client.pem"
  
  tasks:
  - name: store-secret
    with_items:
      - "{{ lookup('dict', secrets) }}"
    include_role:
      name: store-secret