- hosts: localhost
  user: vagrant
  #sudo: yes

  tasks:
    # - name: check that i have log file for all hosts on my local machine
    #   stat: path=/var/log/hosts/{{inventory_hostname}}.log
    #   delegate_to: localhost

    - name: Ansible create file if it doesn't exist example
      file:
        path: "/vagrant/ansible-log.txt"
        state: touch
      become: yes
