- hosts: role_softnas
  remote_user: "{{ softnas_ssh_user | default('ec2-user') }}"
  become: true

  vars:
    skip_packages: false

  tasks:
  - name: ensure file exists
    copy:
      content: ""
      dest: /tmp/updatetype
      force: no

# these packages are required to pass an encrypted string via commandline into a user pass.
  - name: install expect
    package:
      name: expect
      state: present

  - name: install pip
    package:
      name: python-pip
      state: present

  - name: install pexpect
    pip:
      name: pexpect
    become: yes
    
  - name: install passlib
    pip:
      name: passlib
    become: yes

  - name: set user pass
    expect:
      command: passwd softnas
      responses:
        (?i)password: "{{ user_softnas_pw }}"
        (?i)Retype new password: "{{ user_softnas_pw }}"

  - name: ensure file exists
    copy:
      content: ""
      dest: /var/tmp/ansible_log
      force: no

  - name: init authorized_keys
    copy:
      content: ""
      dest: /root/.ssh/authorized_keys
      force: no
    become: true

  # tasks file for roles/init-host
  - name: change hostname
    hostname:
      name: "nas1"
      
  - name: add myself to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1[ \t]+localhost'
      line: "127.0.0.1 localhost nas1"
      state: present

  - name: Set hostname var in bash profile
    lineinfile:
      path: /root/.bash_profile
      line: 'export HOSTNAME=nas1'
      
  # some problems exist in here.  we get # replaced with ; for some reason
  # - name: insert marker start
  #   lineinfile:
  #     path: /var/www/softnas/config/monitoring.ini
  #     insertafter: "^#?# Valid values for SMTP_ENCRYPTION are SSLV2, SSLV3 and TLSV1"
  #     line: "# BEGIN ANSIBLE MANAGED BLOCK"
  #     backup: yes

  # - name: insert marker end
  #   lineinfile:
  #     path: /var/www/softnas/config/monitoring.ini
  #     insertafter: 'SMTP_ENCRYPTION'
  #     line: "# END ANSIBLE MANAGED BLOCK"
  #     create: true
 
  # - name: insert/update email block in /var/www/softnas/config/monitoring.ini
  #   blockinfile:
  #     path: /var/www/softnas/config/monitoring.ini
  #     backup: yes
  #     content: |

  #       NOTIFICATION_EMAIL="queglay@gmail.com"
  #       USE_EXT_SMTP="smtp-relay.gmail.com"
  #       SMTP_MAILSERVER=""
  #       SMTP_PORT="587"
  #       SMTP_USERNAME=""
  #       SMTP_PASSWORD=""
  #       SMTP_ENCRYPTION="tlsv1"

  - name: check if settings file exists
    stat: 
      path: /var/www/softnas/config/general_settings.ini
    register: general_settings

  - name: copy template file
    copy:
      remote_src: true
      src: /var/www/softnas/config/general_settings.ini.prototype
      dest: /var/www/softnas/config/general_settings.ini
    when: not general_settings.stat.exists

  - name: mail settings server in /var/www/softnas/config/general_settings.ini
    lineinfile:
      path: /var/www/softnas/config/general_settings.ini
      regexp: 'smtp_mailserver[ \t]+=[ \t]+'
      line: smtp_mailserver = smtp-relay.gmail.com
      state: present
      create: true

  - name: mail settings server in /var/www/softnas/config/general_settings.ini
    lineinfile:
      path: /var/www/softnas/config/general_settings.ini
      regexp: 'smtp_port[ \t]+=[ \t]+'
      line: smtp_port = 587
      state: present
      create: true

  - name: install nmap
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - nmap
    when: not skip_packages

  - command: "nmap -p {{ item.port }} {{ item.dest }}"
    register: nmap_result
    with_items:
      - { port: '80', dest: 'softnas.com' }
      - { port: '443', dest: 'softnas.com' }
      - { port: '80', dest: 'www.softnas.com' }
      - { port: '443', dest: 'www.softnas.com' }
      - { port: '80', dest: 'mirror.softnas.com' }
      - { port: '443', dest: 'mirror.softnas.com' }

  - debug:
      msg: "{{ item.stdout }}"
    with_items:
      - "{{ nmap_result.results }}"
    when: debug > 0

  - name: Uncomment line from /etc/ssh/sshd_config
    lineinfile:
      path: "/etc/sysconfig/nfs"
      regexp: '^#\s*MOUNTD_PORT=892.*$'
      line: 'MOUNTD_PORT=892'
  
  # # these services need to be restarted if a reboot/update wasn't occuring and changes to volummes are made
  # - service:
  #     name: "{{ item }}"
  #     state: restarted
  #   with_items:
  #     - nfs
  #     - softnas
  #     - monit
    


  - name: login and ack agreement
    #command: "softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd ackagreement"
    shell: |
      softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd ackagreement
    register: softnas_login
  - name: login and ack agreement
    debug:
      var: softnas_login.stdout.split('\n')