- hosts: ansible_control
  remote_user: deployuser
  become: true
  gather_facts: "{{ variable_gather_facts | default('false') }}"

  vars:
    variable_user: deployuser
    set_vpn: false

  roles:
  - ssh-add-public-host

- hosts: firehawkgateway
  remote_user: deployuser
  become: true
  gather_facts: "{{ variable_gather_facts | default('false') }}"

  vars:
    variable_user: deployuser
    set_vpn: false

  roles:
  - ssh-add-public-host