- hosts: localhost
  remote_user: vagrant
  become: true
  gather_facts: no

  vars:
    bastion_ip: false
    local: false
    
    #"{{ variable_user | default('user') }}"

  roles:
  - ssh-add-private-host 