- name: dir permissions on /prod/assets/
  file:
    path: /prod/assets/
    state: directory
    mode: u=wrX,g=wrX,o-rwx
    owner: deadlineuser
    group: syscontrol
    recurse: true
  become: true

- name: dir permissions on /prod/assets/openfirehawk-houdini-tools
  file:
    path: /prod/assets/openfirehawk-houdini-tools
    state: directory
    mode: u=wrX,g=wrX,o-rwx
    owner: deadlineuser
    group: syscontrol
    recurse: true
  become: true

- name: ensure all mounts are present
  command: sudo mount -a
  become_user: deployuser
  connection: local

- name: set bucket for sync
  set_fact:
    bucket: "{{ bucket }}/openfirehawk-houdini-tools"

- name: set user for sync
  set_fact:
    push_user: "deployuser"

- name: s3-sync openfirehawk-houdini-tools push
  import_role:
    name: firehawkvfx.core.s3_sync
  vars:
    mode: "push"
    basedir: "{{ firehawk_sync_source }}"
    exclude: ".git/*"
    filename: "*"
    sync_user: "{{ push_user }}"
  connection: local

- name: set user for sync
  set_fact:
    pull_user: "deadlineuser"

- name: s3-sync openfirehawk-houdini-tools pull
  import_role:
    name: firehawkvfx.core.s3_sync
  vars:
    mode: "pull"
    basedir: "{{ firehawk_sync_target }}"
    exclude: ".git/*"
    filename: "*"
    sync_user: "{{ pull_user }}"

# - name: Sync openfirehawk-houdini-tools to s3 - push
#   shell: |
#     # set -x
#     cd {{ firehawk_sync_source }}
#     aws s3 sync . s3://{{ bucket }}/openfirehawk-houdini-tools/ --include "*" --exclude ".git/*" --no-progress
#   become_user: deployuser
#   connection: local

# - name: Sync openfirehawk-houdini-tools from s3
#   shell: |
#     # set -x
#     mount
#     cat /etc/fstab
#     cd /prod/assets/openfirehawk-houdini-tools

#     aws sts get-caller-identity
#     ls -ltriah
#     touch .test_permissions # Test write permissions
#     rm -fr .test_permissions

#     aws s3 sync s3://{{ bucket }}/openfirehawk-houdini-tools/ . --include "*" --exclude ".git/*" --no-progress
#   become_user: deadlineuser

- name: dir permissions on /prod/assets/hda.  note permissions aren't being set correctly for group for some reason.
  file:
    path: /prod/assets/hda
    state: directory
    owner: deadlineuser
    group: syscontrol
    mode: u=wrX,g=wrX,o-rwx
    recurse: true
  become: true