---
#tasks file for roles/aws-cli

- name: install mkpasswd, pip, pexpect, passlib
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - whois
    - python-pip
    - python-passlib
    - zip

- name: upgrade pip
  shell: |
    pip install --upgrade pip
  become: true

- name: install awscli, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade --user
  become_user: "{{ variable_become_user }}"
  become: true

- name: install pexpect
  pip: 
    name: pexpect
    extra_args: --upgrade --user
  become_user: "{{ variable_become_user }}"
  become: true

- name: install the boto package, force upgrade
  pip: 
    name: boto3
    extra_args: --user
  become_user: "{{ variable_become_user }}"
  become: true

- name: Case insensitive password string match
  expect:
    command: "/home/{{ variable_user }}/.local/bin/aws configure"
    responses:
      .*Access Key ID \[.*\]: "{{ aws_access_key_s3user }}"
      .*Secret Access Key \[.*\]: "{{ aws_secret_key_s3user }}"
      .*region name \[.*\]: "{{ aws_region }}"
      .*output format \[.*\]: json
  become_user: "{{ variable_become_user }}"
  become: true
  no_log: true
  tags:
  - user_access

# example usage:
# ansible-playbook -i ansible/inventory ansible/aws-cli-ec2-install.yaml -v --extra-vars "variable_host=role_node_centos"