---
# tasks file for ansible/roles/aws-new-key
- name: check if a pem key exists
  stat:
    path: "{{ local_key_path }}"
  register: key_result

- name: create a new ec2 key pair, returns generated private key
  ec2_key:
    name: "{{ key_name }}"
    #these must be defined if the module is used.
    AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
    AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"
    ec2_region: "{{ aws_region }}"
  register: ec2_key_result
  when: (key_result.stat.exists == False)

- name: Save private key
  copy:
    content: "{{ ec2_key_result.key.private_key }}"
    dest: "{{ local_key_path }}"
    mode: 0400
  when: (key_result.stat.exists == False) and ec2_key_result.changed