---
# tasks file for ansible/roles/aws-new-key
- name: create a new ec2 key pair, returns generated private key
  ec2_key:
    name: "{{ key_name }}"
    #these must be defined if the module is used.
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    ec2_region: "{{ aws_region }}"
  register: ec2_key_result

- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="{{ local_key_path }}" mode=0600
  when: ec2_key_result.changed