---
# tasks file for fsx_packages

- name: Collect some facts only for ansible_distribution
  setup:
    gather_subset:
      - '!all'
      - 'min'
  tags:
  - always

- name: get key - centos
  get_url:
    url: https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-rpm-public-key.asc
    dest: /tmp/fsx-rpm-public-key.asc
  when: not skip_packages and ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' )

- rpm_key:
    state: present
    key: /tmp/fsx-rpm-public-key.asc
  when: not skip_packages and ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' )

- get_url:
    url: https://fsx-lustre-client-repo.s3.amazonaws.com/el/7/fsx-lustre-client.repo
    dest: /etc/yum.repos.d/aws-fsx.repo
  when: not skip_packages and ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' )

- name: Lustre packages
  package:
    name:
    - kmod-lustre-client
    - lustre-client
    state: present
  when: not skip_packages and ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' )

- name: get key - ubuntu
  get_url:
    url: https://fsx-lustre-client-repo-public-keys.s3.amazonaws.com/fsx-ubuntu-public-key.asc 
    dest: /tmp/fsx-rpm-public-key.asc
  when: not skip_packages and ( ansible_distribution == 'Ubuntu' )