### modify houdini environment vars

- name: Generate houdini.env config from template
  template:
    src: /secrets/houdini{{ houdini_version_item.houdini_major_version }}/houdini_template.env
    dest: /secrets/houdini{{ houdini_version_item.houdini_major_version }}/houdini.env
  become: yes
  connection: local
  tags:
  - cloud-install
  - onsite-install

- name: copy env
  copy:
    src: /secrets/houdini{{ houdini_version_item.houdini_major_version }}/houdini.env
    dest: /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/houdini_from_template.env
  become: true
  tags:
  - cloud-install
  - onsite-install

- name: "Get difference from two houdini.env files"
  command: diff /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/houdini.env /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/houdini_from_template.env
  failed_when: "diff.rc > 1"
  register: diff
  become: yes
  tags:
  - cloud-install
  - onsite-install

- name: debug output
  debug: msg="{{ diff.stdout }}"

- name: houdini_version_item
  debug:
    var: houdini_version_item
  tags:
  - cloud-install
  - onsite-install

- name: copy houdini.env and overwrite
  copy:
    src: /secrets/houdini{{ houdini_version_item.houdini_major_version }}/houdini.env
    dest: "/home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/houdini.env"
  become: true
  tags:
  - cloud-install
  - onsite-install


- name: Add alias for houdini
  lineinfile:
    state: present
    path: /home/deadlineuser/.bashrc
    line: "alias h{{ houdini_version_item.houdini_major_version }}='cwd=\"$(pwd)\" && cd /opt/hfs{{ houdini_version_item.houdini_major_version }}/ && source houdini_setup && cd $cwd && houdinifx'"
    backup: true
    owner: deadlineuser
    regexp: ".*alias h{{ houdini_version_item.houdini_major_version }}=.*"
  become: yes
  tags:
  - cloud-install
  - onsite-install

- name: Add alias for hython
  lineinfile:
    state: present
    path: /home/deadlineuser/.bashrc
    line: "alias hy{{ houdini_version_item.houdini_major_version }}='cwd=\"$(pwd)\" && cd /opt/hfs{{ houdini_version_item.houdini_major_version }}/ && source houdini_setup && cd $cwd && hython'"
    backup: true
    owner: deadlineuser
    regexp: ".*alias hy{{ houdini_version_item.houdini_major_version }}=.*"
  become: yes 
  tags:
  - cloud-install
  - onsite-install

- name: Add alias for houdini_setup environment
  lineinfile:
    state: present
    path: /home/deadlineuser/.bashrc
    line: "alias henv{{ houdini_version_item.houdini_major_version }}='cwd=\"$(pwd)\" && cd /opt/hfs{{ houdini_version_item.houdini_major_version }}/ && source houdini_setup && cd $cwd'"
    backup: true
    owner: deadlineuser
    regexp: ".*alias henv{{ houdini_version_item.houdini_major_version }}=.*"
  become: yes 
  tags:
  - cloud-install
  - onsite-install
  
### end modify houdini environment vars
