- hosts: ansible_control
  remote_user: deployuser
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  vars_files:
    - /deployuser/ansible/group_vars/all/vars
    - vars/main.yml

  tasks:
    - name: test local connection.
      debug:
        msg: "test local connection"

- hosts: role_softnas
  remote_user: "{{ softnas_ssh_user | default('ec2-user') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  vars_files:
    - /deployuser/ansible/group_vars/all/vars
    - vars/main.yml

  tasks:
    - name: test role_softnas connection.
      debug:
        msg: "test role_softnas connection"

- hosts: role_softnas
  remote_user: "{{ softnas_ssh_user | default('ec2-user') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    vars_files_locs: [ "/{{ secrets_path }}/{{ lookup('env','TF_VAR_envtier') }}/ebs-volumes/softnas_ebs_volumes.yaml", "files/softnas_ebs_volumes_{{ lookup('env','TF_VAR_envtier') }}.yaml", "files/softnas_ebs_volumes.yaml" ] # The first file found will be used, allowing the one in your secrets location to override defaults.
  
  vars_files:
    - /deployuser/ansible/group_vars/all/vars
    - vars/main.yml

  tasks:
  - name: aquire vars from secrets path before using defaults for softnas hosts 1
    include_vars: "{{ item }}"
    with_first_found: "{{ vars_files_locs }}"
    tags:
    - always

  - name: all volumes retrieved
    debug:
      var: "{{ mounts }}"

  - name: search for existing pools, to later create if missing
    stat:
      path: "/{{ item.pool_name }}/"
    register: existing_pools
    with_items:
      - "{{ exports }}"

  - name: result existing_pools
    debug:
      var: existing_pools

  - include_role:
      name: softnas-ebs-pool-create
    when: not outer_item.stat.exists
    with_items:
      - "{{ existing_pools.results }}"
    loop_control:
      loop_var: outer_item

  - name: search for existing volumes, to later create if missing
    stat:
      path: "/{{ item.pool_name }}/{{ item.volume_name }}/"
    register: existing_volumes
    with_items:
      - "{{ exports }}"

  - name: result existing_volumes
    debug:
      var: existing_volumes

  - include_role:
      name: softnas-ebs-volume-create
    when: not outer_item.stat.exists
    with_items:
      - "{{ existing_volumes.results }}"
    loop_control:
      loop_var: outer_item