- name: clean known hosts
  shell: "ssh-keygen -f /home/vagrant/.ssh/known_hosts -R {{ private_ip }}"
  become: true
  become_user: vagrant

- name: msg delegate to bastion ip
  debug:
    msg: "{{ bastion_ip }}"
  when: bastion_ip

- name: msg delegate to get key for private_ip
  debug:
    msg: "{{ private_ip }}"

- name: bastion_ip
  debug:
    var: bastion_ip

- name: delegate keyscan to add keys from remote subnet via bastion host.
  command: "ssh-keyscan {{ private_ip }}"
  register: new_host_fingerprint
  delegate_to: "centos@{{ bastion_ip }}"
  remote_user: centos
  become_user: centos
  become: true
  when: bastion_ip 

- name: delegate keyscan to add keys from remote subnet on this host.
  command: "ssh-keyscan {{ private_ip }}"
  register: new_host_fingerprint
  become: true
  when: local

- name: retrieved new_host_fingerprint
  debug:
    var: "{{ new_host_fingerprint }}"

- name: add keyscan to known hosts
  lineinfile:
    dest: /home/vagrant/.ssh/known_hosts
    line: "{{ item }}"
  with_items: "{{ new_host_fingerprint.stdout_lines }}"
  become: true
  become_user: vagrant