### HOUDINI UNIT TEST ###

- hosts: "{{ variable_host | default('role_node_centos') }}"
  remote_user: "{{ variable_connect_as_user | default('centos') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars_files:
    - /deployuser/ansible/group_vars/all/vars
    - vars/main.yml
    - /secrets/overrides/ansible/collections/firehawkvfx/houdini/vars/main.yml

  vars:
    # the become sudo pass is only relevent for local installation if required on the host specified.
    ansible_become_pass: "{{ user_deadlineuser_pw }}"
    
    variable_user: centos
    bastionip: "{{ groups['bastionip'][0] }}"
    

  roles:
  - role: houdini_openfirehawk_houdini_tools_sync