---
# tasks file for roles/init-packages
- name: ansible distro
  debug:
    var: ansible_distribution

- name: install mkpasswd, pip, pexpect, passlib
  package:
    name:
    - whois
    - python-pip
    - python-passlib
    - zip
    - openvpn
    - rng-tools
    - gpgv2
    state: present

#nfs-common is used for showmount

- name: install pexpect for rhel / centos,
  pip:
    name: pexpect
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

# Enterprise Linux'
# Above is for RHEL and Centos, the following is for Debian/Ubuntu:

- name: install pexpect for ubuntu
  package:
    name:
    - python-pexpect
    - nfs-common
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'