---
# tasks file for roles/houdini-install

- name: houdini_version_item
  debug:
    var: houdini_version_item

- name: "set permissions and ensure dir exists /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
  file:
    path: "/home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
    state: directory
    mode: u=rwX,g=r
    owner: deadlineuser
    group: deadlineuser
  become: true

- name: "copy houdini-scripts to /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
  copy:
    src: /vagrant/modules/node_centos/modules/houdini-scripts/
    dest: "/home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
    directory_mode: yes
    owner: deadlineuser
  become: true

- name: "set permissions on /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
  file: 
    dest: "/home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
    owner: deadlineuser 
    group: deadlineuser
    mode: u=rwX,g=r
    recurse: yes
  become: true


- name: "set permissions on /home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/"
  file: 
    dest: "/home/deadlineuser/houdini{{ houdini_version_item.houdini_major_version }}/scripts/menus/"
    owner: deadlineuser 
    group: deadlineuser
    mode: u=rwX,g=r
    recurse: yes
  become: true

- set_fact:
    houdini_linux_filename: "{{ houdini_version_item.houdini_linux_filename }}"

- name: Query houdini filename - Houdini python script
  shell: |
    cd /opt/houdini_install_script/
    python /opt/houdini_install_script/houdini_install.py -u {{ sesi_username }} -p {{ sesi_password }} -i /opt/houdini -b {{ houdini_version_item.houdini_build }} -t {{ download_to_dir }} -q true -f {{ houdini_linux_filename }}
  register: houdini_query_out
  become: true
  when: houdini_version_item.houdini_auto_version

- name: Python output
  debug:
    var: item
  with_items:
  - "{{ houdini_query_out.stdout_lines }}"
  when: houdini_version_item.houdini_auto_version


- set_fact:
    houdini_linux_filename: "{{ item | regex_search(regexp) }}"
  vars:
    regexp: '(houdini.*.tar.*)'
  with_items:
  - "{{ houdini_query_out.stdout_lines }}"
  when: houdini_version_item.houdini_auto_version

- name: Houdini filename to install from sidefx website result
  debug:
    var: houdini_linux_filename

- name: Sync houdini from s3 if exist - pull
  shell: |
    set -x
    cd {{ download_to_dir }}/
    ~/.local/bin/aws s3 sync s3://{{ bucket }}/ . --exclude "*" --include "{{ houdini_linux_filename }}"
  become_user: "{{ variable_user }}"

- name: Auto download and install Houdini with python script - auto version
  shell: |
    cd /opt/houdini_install_script/
    sudo python /opt/houdini_install_script/houdini_install.py -u {{ sesi_username }} -p {{ sesi_password }} -i /opt/houdini -b {{ houdini_version_item.houdini_build }} -t {{ download_to_dir }} -q false
  register: houdini_install_out
  become: true
  when: not skip_install and houdini_version_item.houdini_auto_version

- debug:
    msg:  "{{ houdini_install_out.stdout }}"
  when: not skip_install and houdini_version_item.houdini_auto_version

- name: Install Houdini with python script - specific existing version from s3 bucket
  shell: |
    cd /opt/houdini_install_script/
    sudo python /opt/houdini_install_script/houdini_install.py -u {{ sesi_username }} -p {{ sesi_password }} -i /opt/houdini -b {{ houdini_version_item.houdini_build }} -t {{ download_to_dir }} -q false -f {{ houdini_linux_filename }}
  register: houdini_install_out
  become: true
  when: not skip_install and not houdini_version_item.houdini_auto_version

- debug:
    msg:  "{{ houdini_install_out.stdout }}"
  when: not skip_install and not houdini_version_item.houdini_auto_version

- name: "setup licensing mode will write to /opt/hfs{{ houdini_version_item.houdini_major_version }}/houdini/Licensing.opt"
  shell: |
    cd /opt/hfs{{ houdini_version_item.houdini_major_version }}
    sudo sed -i '/licensingMode = sesinetd/s/^# //g' /opt/hfs{{ houdini_version_item.houdini_major_version }}/houdini/Licensing.opt
    sudo cat /opt/hfs{{ houdini_version_item.houdini_major_version }}/houdini/Licensing.opt
  register: houdini_hserver_out
  become: true
  when: not skip_install

- name: setup licensing server ip as deadline user will write to $HOME/.sesi_licenses.pref
  shell: |
    cd /opt/hfs{{ houdini_version_item.houdini_major_version }}
    source ./houdini_setup
    hserver
    hserver -S {{ houdini_license_server_address }}
    hserver -l
    echo $HOME
  register: houdini_hserver_deadlineuser_out
  become_user: deadlineuser
  when: not skip_install

# ### server install
# - name: check if hserver file exists
#   stat: 
#     path: /opt/hfs17.5/bin/hserver
#   register: hserver_check
#   become: true

# - name: Stop licensing server if already running / installed.  Please ignore any error if hserver not running.
#   shell: |
#     /opt/hfs17.5/bin/hserver -q
#   ignore_errors: yes
#   become: true
#   when: hserver_check.stat.exists == true

# - name: install houdini
#   shell: |
#     set -x
#     sudo chmod 600 /var/tmp/houdini-17.5.173-linux_x86_64_gcc6.3.tar
#     cd /var/tmp
#     sudo mkdir houdini_installer
#     sudo tar -xvf houdini-17.5.173-linux_x86_64_gcc6.3.tar -C houdini_installer --strip-components 1
#     cd houdini_installer
#     sudo ./houdini.install --auto-install --accept-EULA --install-houdini --install-license --no-local-licensing --install-hfs-symlink
#   register: houdini_install_out
#   become: true

# - debug:
#     msg:  "{{ houdini_install_out.stdout }}"

# - name: setup licensing mode
#   shell: |
#     cd /opt/hfs17.5
#     sudo sed -i '/licensingMode = sesinetd/s/^# //g' /opt/hfs17.5/houdini/Licensing.opt
#     sudo cat /opt/hfs17.5/houdini/Licensing.opt
#     /opt/hfs17.5/bin/hserver
#   become: true
# ### end server install

# After install sync houdini download with bucket

- name: ensure the houdini installer exist in the s3 bucket.  Push if it doesn't.
  s3_sync:
    bucket: "installers.{{ public_domain }}"
    file_root: "{{ download_to_dir }}"
    include: "{{ houdini_linux_filename }}"
    aws_access_key: "{{ aws_access_key_s3user }}"
    aws_secret_key: "{{ aws_secret_key_s3user }}"
    region: "{{ aws_region }}"
    mode: push
  tags:
    - sync_installers

- name: comment out file to enforce env
  copy:
    dest: /etc/profile.d/houdini_init.sh
    content: |
      # cwd="$(pwd)" && cd /opt/hfs{{ houdini_version_item.houdini_major_version }}/ && source ./houdini_setup && cd $cwd
    mode: u=rw,g=r,o=r
    owner: root
    group: root 
  become: true
  tags:
    - enforce_houdini_env_vars