- hosts: localhost

  tasks:
    - name: Ensures dir exists
      file:
        path: /home/deadlineuser/Downloads/Deadline-10.0.23.4-linux-installers/
        state: directory
        owner: deadlineuser
      become: yes

    - name: Ensures dir exists
      file:
        path: /opt/Thinkbox/certs
        state: directory
        owner: deadlineuser
      become: yes

    - name: Extract
      unarchive:
        src: /vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar
        dest: /home/deadlineuser/Downloads/Deadline-10.0.23.4-linux-installers/
        owner: deadlineuser
        mode: u+x
      become: yes

    - name: set permissions
      file:
        path: /opt/Thinkbox/DeadlineDatabase10/certs/Deadline10Client.pfx
        mode: "u+r"
        owner: deadlineuser

      # /home/deadlineuser/Downloads/Deadline-10.0.23.4-linux-installers/DeadlineRepository-10.0.23.4-linux-x64-installer.run --mode unattended --debuglevel 2 --prefix /opt/Thinkbox/DeadlineRepository10 --setpermissions true --installmongodb true --dbOverwrite true --mongodir /opt/Thinkbox/DeadlineDatabase10 --dbListeningPort 27017 --certgen_outdir /opt/Thinkbox/DeadlineDatabase10/certs --certgen_password @WhatTime --createX509dbuser true --requireSSL true --dbhost openfirehawkserver.firehawkvfx.com --dbport 27017 --dbuser deadlineuser --dbpassword @WhatTime --dbauth true --dbcertpass @WhatTime --dbssl true
    - name: install deadline rcs
      command: /home/deadlineuser/Downloads/Deadline-10.0.23.4-linux-installers//DeadlineClient-10.0.23.4-linux-x64-installer.run --mode unattended --debuglevel 2 --prefix /opt/Thinkbox/Deadline10 --connectiontype Repository --repositorydir /opt/Thinkbox/DeadlineRepository10/ --proxyrootdir openfirehawkserver.firehawkvfx.com:4433 --dbsslpassword @WhatTime --proxycertificate /opt/Thinkbox/certs/Deadline10RemoteClient.pfx --proxycertificatepassword @WhatTime --licensemode UsageBased --daemonuser deadlineuser --connserveruser deadlineuser --httpport 8080 --tlsport 4433 --enabletls true --tlscertificates generate  --generatedcertdir /opt/Thinkbox/certs/ --clientcert_pass @WhatTime
      become: true
      #shell: /home/deadlineuser/Downloads/DeadlineRepository-10.0.23.4-linux-x64-installer.run --mode unattended --debuglevel 2 --prefix /opt/Thinkbox/DeadlineRepository10 --setpermissions true --installmongodb true --dbOverwrite true --mongodir /opt/Thinkbox/DeadlineDatabase10 --dbListeningPort 27017 --certgen_outdir /opt/Thinkbox/DeadlineDatabase10/certs --certgen_password @WhatTime --createX509dbuser true --requireSSL true --dbhost openfirehawkserver.firehawkvfx.com --dbport 27017 --dbuser deadlineuser --dbpassword @WhatTime --dbauth true --dbcertpass @WhatTime --dbssl true

