- name: Test output
  debug:
    msg: "variable_user:{{ variable_user }}"
    
- name: Test output
  debug:
    msg: "using bucket s3://{{ bucket }}/"

- name: Sync S3 # warning: there appears to be a bug with ansible that may result in variable user being defined at the include_role level not setting the variable_user var correctly.  consider this if errors should occur.
  shell: |
    # set -x
    cd ~
    echo "become user {{ variable_user }}"
    echo "whoami $(whoami)"
    echo "pwd: $(pwd)"
    cd {{ basedir }}
    exit_code=$?
    echo "pwd: $(pwd)"
    if [[ ! "$exit_code" -eq 0 ]]; then echo "Failed: Couldn't cd to base directory."; exit 1; fi
    
    test_file () {
      local filename="$1"
      echo "ls bucket: {{ bucket }}"
      aws s3 ls s3://{{ bucket }}/
      wordcount=`aws s3 ls s3://{{ bucket }}/|grep {{ filename }}|wc -c`
      if [[ "${wordcount}" -eq 0 ]]; then
        file_in_bucket=true
      else
        file_in_bucket=false
      fi
    }
    test_file "$filename"
    
    if [[ "$file_in_bucket" == true ]]; then
      if [[ {{ mode }} == 'push' ]]; then
        echo "Sync Push: File not yet present in S3 bucket, will push."
        if [ -f "{{ filename }}" ]; then
          aws s3 sync . s3://{{ bucket }}/ --exclude "*" --include "{{ filename }}" --no-progress
          sleep 3 # After push, the file may not be immediately present to s3 ls.  Wait a few seconds first.
          test_file "$filename"
          if [[ "$file_in_bucket" == false ]]; then
            echo "Failed: File not present in bucket after attempt to push."
            exit 1
          fi
          echo "Success: File is present in bucket after push."
          exit 0
        else 
          echo "Failed: {{ filename }} does not exist on disk, won't push."
          exit 1
        fi
        
      else
        echo "Won't pull, File not present in S3 bucket."
        exit 0
      fi
    else
      if [[ {{ mode }} == 'push' ]]; then
        echo "Sync Push: File already present in S3 bucket, won't push."
        exit 0
      else
        echo "Sync Pull: File present in S3 bucket..."
        if [ -f "{{ filename }}" ]; then
          echo "{{ filename }} File already present.  Won't Pull"
          exit 0
        else 
          aws s3 sync s3://{{ bucket }}/ . --exclude "*" --include "{{ filename }}" --no-progress
          if [ -f "{{ filename }}" ]; then
            echo "Success: File is present on disk after pull."
            exit 0
          else
            echo "Failed: Pull not present on disk after attempt to pull."
            exit 1
          fi
        fi
      fi
    fi
  register: output
  become_user: "{{ variable_user }}"
  changed_when:
    - '"File already present" not in output.stdout'
  args:
    executable: /bin/bash
