---
# tasks file for roles/deadlinedb
- name: "Ensures tar exists {{ deadline_linux_installers_tar }}"
  stat:
    path: "{{ deadline_linux_installers_tar }}"
  register: deadline_linux_installers_tar_stat
  become: yes

- name: "Test: Fail if not existing tar."
  fail:
    msg: "Bailing out: You need to place the installer in the download directory.  Installer not found - {{ deadline_linux_installers_tar }}"
  when: deadline_linux_installers_tar_stat.stat.exists == false or deadline_linux_installers_tar_stat.stat.isdir == True

- name: Ensures dir exists
  file:
    path: "/home/deadlineuser/Downloads/{{ deadline_linux_basename }}"
    state: directory
    owner: deadlineuser
  become: yes

- name: Ensures dir exists
  file:
    path: /opt/Thinkbox/certs
    state: directory
    owner: deadlineuser
  become: yes

- name: Extract
  unarchive:
    src: "{{ deadline_linux_installers_tar }}"
    dest: "/home/deadlineuser/Downloads/{{ deadline_linux_basename }}"
    owner: deadlineuser
    mode: u+x
  become: yes
  tags:
  - install

- name: "Ansible find files in subdirectory downloads"
  find:
    paths: /home/deadlineuser/Downloads/{{ deadline_linux_basename }}
    patterns: "*DeadlineRepository-{{ deadline_version }}-linux-x64-installer.run"
  register: files_matched
  become: true
  tags:
  - install
  - sync_installers

- name: set permissions
  file:
    path: "{{ files_matched.files[0].path }}"
    mode: +r+x-w
    owner: deadlineuser
  become: true
  tags:
  - install

- name: install deadline db
  shell: |
    set -x
    cd /home/deadlineuser/Downloads/
    {{ files_matched.files[0].path }} --mode unattended --debuglevel 2 --prefix /opt/Thinkbox/DeadlineRepository10 --setpermissions true --installmongodb true --dbOverwrite true --mongodir /opt/Thinkbox/DeadlineDatabase10 --dbListeningPort 27017 --certgen_outdir /opt/Thinkbox/DeadlineDatabase10/certs --certgen_password {{ deadline_proxy_certificate_password }} --createX509dbuser true --requireSSL true --dbhost {{ openfirehawkserver }} --dbport 27017 --dbuser {{ user_deadlineuser_name }} --dbpassword {{ deadline_proxy_certificate_password }} --dbauth true --dbcertpass {{ deadline_proxy_certificate_password }} --dbssl true
  register: deadline_db_install_output_shell
  become: true
  tags:
  - install

- name: ensure the deadline linux installer tar exists in the s3 bucket.  Push if it doesn't.
  s3_sync:
    bucket: "installers.{{ public_domain }}"
    file_root: "{{ deadline_linux_installers_tar | dirname }}"
    include: "{{ deadline_linux_installers_tar | basename }}"
    aws_access_key: "{{ aws_access_key_s3user }}"
    aws_secret_key: "{{ aws_secret_key_s3user }}"
    region: "{{ aws_region }}"
    mode: push
  become: true
  tags:
  - install
  - sync_installers

- name: check deadline db install output
  debug:
    msg: "{{ deadline_db_install_output_shell.stdout }}"
  tags:
  - install

- name: Restart service for deadlinedb
  service:
    name: Deadline10db
    state: restarted
  become: true
  tags:
  - install

- name: show version list
  debug:
    var: houdini_major_version_list

- name: setup houdini plugin for each major version.  this occurs after deadline install and with install of houdini
  include_role:
    name: 'deadlinedb-houdini-plugins'
  loop: "{{ houdini_major_version_list }}"
  loop_control:
    loop_var: houdini_major_version