---
# tasks file for ./ansible/roles/pip
# these packages are required to pass an encrypted string via commandline into a user pass and are suited to centos, and also for aws cli.

- name: Add epel repository for centos7
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_repo_url }}"
    gpgkey: "{{ epel_repo_gpg_key_url }}"
    enabled: yes
  become: true
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ansible_distribution_major_version > '6'
  tags:
  - add-epel

- name: Add epel repository for centos6 and lower
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_repo_url }}"
    gpgkey: "{{ epel_repo_gpg_key_url }}"
    enabled: yes
  become: true
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' ) and ansible_distribution_major_version <= '6'
  tags:
  - add-epel

- name: upgrade all yum packages
  yum:
    name: '*'
    state: latest
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Upgrade all apt packages
  apt:
    name: "*"
    state: latest
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install epel-release
  package:
    name: epel-release
    state: latest
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: install pip
  package:
    name: python-pip
    state: latest
  become: true

- name: upgrade pip
  pip: 
    name: pip
    extra_args: --upgrade
  become: true

- name: uninstall urllib3 because of conflict with rhel 8 packages
  pip:
    name: urllib3
    state: absent
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: install python-urllib3 package
  package:
    name: 'python-urllib3'
    state: present
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: upgrade pyopenssl
  pip: 
    name: pyopenssl
    extra_args: --upgrade
  become: true

- name: remove cryptography and reinstall to fix a bug with boto and pip
  pip: 
    name: cryptography
    state: absent
  become: true

- name: upgrade cryptography
  pip: 
    name: cryptography
    extra_args: --upgrade
  become: true

- name: upgrade paramiko to fix a bug with boto and pip
  pip: 
    name: paramiko
    extra_args: --upgrade
  become: true

- name: install pexpect
  pip:
    name: pexpect
  become: yes
  
- name: install passlib
  pip:
    name: passlib
  become: yes

- name: install requests
  pip:
    name: requests
  become: yes

- name: install boto
  pip: 
    name: boto
  become: true

- name: install boto3
  pip: 
    name: boto3
  become: true