---
# tasks file for ./ansible/roles/pip
# these packages are required to pass an encrypted string via commandline into a user pass and are suited to centos, and also for aws cli.

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_repo_url }}"
    gpgkey: "{{ epel_repo_gpg_key_url }}"
    enabled: yes
  become: true

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: install epel-release
  package:
    name: epel-release
    state: latest
  become: true

- name: install pip
  package:
    name: python-pip
    state: latest
  become: true

- name: upgrade pip
  pip: 
    name: pip
    extra_args: --upgrade
  become: true

- name: uninstall urllib3 because of conflict with rhel 8 packages
  pip:
    name: urllib3
    state: absent
  become: yes

- name: install python-urllib3 with yum 
  yum:
    name: 'python-urllib3'
    state: present
  become: yes

- name: install pexpect
  pip:
    name: pexpect
  become: yes
  
- name: install passlib
  pip:
    name: passlib
  become: yes

- name: install boto
  pip: 
    name: boto
  become: true

- name: install boto3
  pip: 
    name: boto3
  become: true