- name: provide temporary steps to work around this failure.
  debug:
    msg: currently the expect module isn't working here.  try to enter this in a shell to validate a password first.  "keybase pgp encrypt -m 'secret' | keybase pgp decrypt"

- name: Case insensitive password string match
  expect:
    chdir: /vagrant
    command: '/bin/bash -c "echo {{ spot_secret }} | base64 --decode | keybase pgp decrypt"'
    responses:
      PGP Decryption: "{{ keybase_secret }}"
      
  become_user: vagrant
  connection: local
  register: spot_secret_output
  #no_log: true

- set_fact:
    spot_secret_key: "{{ spot_secret_output.stdout }}"
  #no_log: true

- debug:
    msg: "warning, multiple subnets in the json spot fleet template may cause errors"

- name: init spot secret keys
  shell: | 
    set -x
    cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"PluginEnabled": "1"}})'
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"DlInit.State": "Global Enabled"}})'
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"PluginEnabled": "1"}})'

    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"DlInit.AccessID": "{{ spot_access_key_id }}"}})'
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"DlInit.SecretKey": "{{ spot_secret_key }}"}})'
  become: true
  #register: deadline_db
  with_items:
  - insert
  - update
  no_log: true

# - name: init spot root keys debug only
#   shell: | 
#     set -x
#     cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
#     ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"DlInit.AccessID": "{{ aws_access_key }}"}})'
#     ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.EventPluginSettingsCollection.{{ item }}({"_id": "spot"},{$set:{"DlInit.SecretKey": "{{ aws_secret_key }}"}})'
#   become: true
#   register: deadline_db
#   with_items:
#   - insert
#   - update
#   #no_log: true