---
# tasks file for roles/init-host
- name: change hostname
  hostname:
    name: "{{ openfirehawkserver_name }}"

# - name: add myself to /etc/hosts
#   lineinfile:
#     dest: /etc/hosts
#     line: "{{ openfirehawkserver }} {{ openfirehawkserver_name }}"
#     state: present

- name: insert/update block in /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.hostname }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.hostname }}"
  with_items:
    - { ip: "{{ openfirehawkserver }}", hostname: "{{ openfirehawkserver_name }}" }

- name: check if hosts template exists
  stat:
    path: /vagrant/secrets/hosts
  register: hosts_template

- name: insert/update block in /etc/hosts from template
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.content }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.path }}"
  with_items:
    - { path: "/vagrant/secrets/hosts", content: "{{ lookup('file', '/vagrant/secrets/hosts') }}" }
  when: hosts_template.stat.exists == True

- name: Allow new lines from ansible shell output.  Logout or reboot for this to take effect.
  lineinfile:
    path: /etc/environment
    line: "ANSIBLE_STDOUT_CALLBACK=debug"
    create: yes
    
- name: insert marker start
  lineinfile:
    path: /etc/rc.local
    insertafter: "^#?.By default.*$"

    line: "# BEGIN ANSIBLE MANAGED BLOCK"
    backup: yes

- name: insert marker end
  lineinfile:
    path: /etc/rc.local
    insertafter: "# BEGIN ANSIBLE MANAGED BLOCK"
    line: "# END ANSIBLE MANAGED BLOCK"
    create: true

- name: insert/update block in /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    backup: yes
    content: |
      #promiscuous mode required for routing
      /sbin/ifconfig enp0s8 up
      /sbin/ifconfig enp0s8 promisc

- name: execute and check with netstat
  shell: |
    /etc/rc.local
    netstat -i
  register: netstatout
  become: true

- debug:
    msg: "{{ netstatout.stdout }}"