---
# tasks file for roles/init-host
- name: change hostname to myserver
  hostname:
    name: "openfirehawkserver.firehawkvfx.com"
- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost openfirehawkserver.firehawkvfx.com"
    state: present

- name: Allow new lines from ansible shell output.  Logout or reboot for this to take effect.
  lineinfile:
    path: /etc/environment
    line: "ANSIBLE_STDOUT_CALLBACK=debug"
    create: yes

    