---
# tasks file for roles/init-host
- name: change hostname to myserver
  hostname:
    name: "openfirehawkserver.{{ public_domain_prod }}"

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: "127.0.0.1 localhost openfirehawkserver.{{ public_domain_prod }}"
    state: present

- name: Allow new lines from ansible shell output.  Logout or reboot for this to take effect.
  lineinfile:
    path: /etc/environment
    line: "ANSIBLE_STDOUT_CALLBACK=debug"
    create: yes
    
- name: insert marker start
  lineinfile:
    path: /etc/rc.local
    insertafter: "^#?By default this script does nothing.*$"

    line: "# BEGIN ANSIBLE MANAGED BLOCK"
    backup: yes

- name: insert marker end
  lineinfile:
    path: /etc/rc.local
    insertafter: "# BEGIN ANSIBLE MANAGED BLOCK"
    line: "# END ANSIBLE MANAGED BLOCK"
    create: true

- name: insert/update block in /etc/fstab
  blockinfile:
    path: /etc/fstab
    backup: yes
    content: |
      #promiscuous mode required for routing
      /sbin/ifconfig enp0s8 up
      /sbin/ifconfig enp0s8 promisc