- name: install expect module
  package:
    name: expect
  become: true

- name: encrypt test secrets
  shell:
    keybase pgp encrypt -m "this is a decrypted test secret" | base64
  become_user: vagrant
  register: pgp_secret_encrypted

- name: Run expect to wait for a keybase pass and decrypt - first time is dirty output.
  shell: |
    test=$(keybase pgp encrypt -m "this is a decrypted test secret" | base64)
    /vagrant/scripts/pgp-expect.sh {{ keybase_secret | regex_escape() }} {{ pgp_secret_encrypted.stdout | regex_escape() }}
  become_user: vagrant
  connection: local
  no_log: true

- name: Run expect to wait for a keybase pass and decrypt - collect output.
  shell: |
    test=$(keybase pgp encrypt -m "this is a decrypted test secret" | base64)
    /vagrant/scripts/pgp-expect.sh {{ keybase_secret | regex_escape() }} {{ pgp_secret_encrypted.stdout | regex_escape() }}
  become_user: vagrant
  connection: local
  register: pgp_secret_output
  no_log: true

- name: Test debug
  debug:
    var: pgp_secret_output.stdout

- name: Test if encryption failed
  fail:
    msg: The encryption and decryption test failed.
  when: pgp_secret_output.stdout != 'this is a decrypted test secret'

- name: Test passed if text 'this is a decrypted test secret' is readable in output.
  debug:
    var: pgp_secret_output.stdout
  when: pgp_secret_output.stdout == 'this is a decrypted test secret'