# Warning: this bucket and its policies is shared by the production and dev environment.
# changes will affect all environments simultaneusly.

- name: Generate bucket policy from template
  template:
    src: bucket_policy.template.json
    dest: "{{ policy_file }}"
  become: yes
  connection: local

- name: output
  debug:
    mgs: "{{ lookup('file', {{ policy_file }} ) }}"

- name: "Ensure an s3 bucket exists - with the aws user credentials - {{ installers_bucket }}"
  s3_bucket:
    name: "{{ installers_bucket }}"
    region: "{{ aws_region }}"
    policy: "{{ lookup('file', {{ policy_file }} ) }}"
  become: false
  environment: # this bucket is shared between dev and prod accounts to ensure installers are available to both accounts.
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID_prod') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY_prod') }}"