- hosts: localhost

  vars_prompt:
    - name: "deadline_linux_installers_tar"
      prompt: "What is the path to the deadline linux installers .tar?"
      default: "/vagrant/downloads/Deadline-10.0.23.4-linux-installers.tar"
      private: no

  vars:
    no_extension: "{{ deadline_linux_installers_tar | splitext | first }}"
    basename: "{{ no_extension.split('/')[-1] }}"

  tasks:
    #- include_tasks: modules/install-terraform.yaml
    - include_tasks: modules/install-deadlinedb.yaml
      vars:
        deadline_linux_installers_tar: "{{ deadline_linux_installers_tar }}"
        no_extension: "{{ no_extension }}"
        basename: "{{ basename }}"
      #import_playbook: modules/install-deadlinedb.yaml deadline_linux_installers_tar='{{deadline_linux_installers_tar}}'
      # - name: install deadlinercs
      #   import_playbook: modules/install-deadlinercs.yaml deadline_linux_installers_tar='{{deadline_linux_installers_tar}}'
