- hosts: firehawkgateway
  remote_user: deployuser
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true

  vars:
    state: restarted

  tasks:

  - name: restart openvpn
    service: 
      name: openvpn
      state: restarted
    when: state == 'restarted'

  - name: stop openvpn
    service: 
      name: openvpn
      state: stopped
    when: state == 'stopped'