- hosts: ansible_control
  become: true

  vars:
    bastionip: "{{ groups['bastionip'][0] }}"

  tasks:
  - name: echo bastion public ip
    debug:
      msg: "{{ item }}"
    with_items:
      - "{{ bastionip }}"
  
  - name: Write the new ec2 instance host key to known hosts
    shell: "ssh-keyscan -H {{ bastionip }} >> ~/.ssh/known_hosts"

- hosts: localhost
  remote_user: vagrant
  become: true
  gather_facts: no

  vars:
    bastionip: "{{ groups['bastionip'][0] }}"

  tasks:
  - name: delegate keyscan to add keys from remote subnet via bastion host.
    command: "ssh-keyscan {{ groups['role_softnas'][0] }}"
    register: new_host_fingerprint
    delegate_to: "centos@{{ groups['bastionip'][0] }}"
    #remote_user: centos
  - debug:
      msg: "{{ new_host_fingerprint.stdout_lines }}"

  - name: add keyscan to known hosts
    lineinfile:
      dest: /home/vagrant/.ssh/known_hosts
      line: "{{ item }}"
    with_items: "{{ new_host_fingerprint.stdout_lines }}"

- hosts: role_softnas
  remote_user: centos
  become: true

  vars:
    bastionip: "{{ groups['bastionip'][0] }}"

  tasks:
  - name: ensure file exists
    copy:
      content: ""
      dest: /tmp/updatetype
      force: no

  - name: install mkpasswd
    package:
      name: expect
      state: present

  - name: install pip
    package:
      name: python-pip
      state: present

  - name: install pexpect
    pip:
      name: pexpect
    become: yes
    
  - name: install passlib
    pip:
      name: passlib
    become: yes

  - name: set user pass
    expect:
      command: passwd softnas
      responses:
        (?i)password: "{{ user_softnas_pw }}"
        (?i)Retype new password: "{{ user_softnas_pw }}"

  - name: multiline test
    #command: "softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd executeupdate"
    shell: |
      softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd checkupdate
    register: softnas_multiline_test

  - name: multiline test
    debug:
      var: softnas_multiline_test.stdout.split('\n')
      

  - name: ensure file exists
    copy:
      content: ""
      dest: /var/tmp/ansible_log
      force: no

  - name: init authorized_keys
    copy:
      content: ""
      dest: /root/.ssh/authorized_keys
      force: no
    become: true

  # tasks file for roles/init-host
  - name: change hostname
    hostname:
      name: "nas1.firehawkvfx.com"
      
  - name: add myself to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1[ \t]+localhost'
      line: "127.0.0.1 localhost nas1.firehawkvfx.com"
      state: present

  - name: Set hostname var in bash profile
    lineinfile:
      path: /root/.bash_profile
      line: 'export HOSTNAME=nas1.firehawkvfx.com'
      

  - name: insert marker start
    lineinfile:
      path: /var/www/softnas/config/monitoring.ini
      insertafter: "^#?# Valid values for SMTP_ENCRYPTION are SSLV2, SSLV3 and TLSV1"
      #insertafter: .*Valid values for SMTP_ENCRYPTION are SSLV2, SSLV3 and TLSV1.*
      line: "# BEGIN ANSIBLE MANAGED BLOCK"
      backup: yes

  - name: insert marker end
    lineinfile:
      path: /var/www/softnas/config/monitoring.ini
      insertafter: 'SMTP_ENCRYPTION'
      line: "# END ANSIBLE MANAGED BLOCK"
      create: true
 
  - name: insert/update email block in /var/www/softnas/config/monitoring.ini
    blockinfile:
      path: /var/www/softnas/config/monitoring.ini
      backup: yes
      #marker: "#### ANSIBLE MANAGED BLOCK ####"
      #insertafter: "<body>"
      content: |

        NOTIFICATION_EMAIL="queglay@gmail.com"
        USE_EXT_SMTP="smtp-relay.gmail.com"
        SMTP_MAILSERVER=""
        SMTP_PORT="587"
        SMTP_USERNAME=""
        SMTP_PASSWORD=""
        SMTP_ENCRYPTION="tlsv1"

  - name: check if settings file exists
    stat: 
      path: /var/www/softnas/config/general_settings.ini
    register: general_settings

  - name: copy template file
    copy:
      remote_src: true
      src: /var/www/softnas/config/general_settings.ini.prototype
      dest: /var/www/softnas/config/general_settings.ini
    when: not general_settings.stat.exists

  - name: mail settings server in /var/www/softnas/config/general_settings.ini
    lineinfile:
      path: /var/www/softnas/config/general_settings.ini
      regexp: 'smtp_mailserver[ \t]+=[ \t]+'
      line: smtp_mailserver = smtp-relay.gmail.com
      state: present
      create: true

  - name: mail settings server in /var/www/softnas/config/general_settings.ini
    lineinfile:
      path: /var/www/softnas/config/general_settings.ini
      regexp: 'smtp_port[ \t]+=[ \t]+'
      line: smtp_port = 587
      state: present
      create: true

  - name: install nmap
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - nmap

  - command: "nmap -p {{ item.port }} {{ item.dest }}"
    register: nmap_result
    with_items:
      - { port: '80', dest: 'softnas.com' }
      - { port: '443', dest: 'softnas.com' }
      - { port: '80', dest: 'www.softnas.com' }
      - { port: '443', dest: 'www.softnas.com' }
      - { port: '80', dest: 'mirror.softnas.com' }
      - { port: '443', dest: 'mirror.softnas.com' }

  - debug:
      msg: "{{ item.stdout }}"
    with_items:
      - "{{ nmap_result.results }}"

  - name: Uncomment line from /etc/ssh/sshd_config
    lineinfile:
      path: "/etc/sysconfig/nfs"
      regexp: '^#\s*MOUNTD_PORT=892.*$'
      line: 'MOUNTD_PORT=892'
  
  # - service:
  #     name: "{{ item }}"
  #     state: restarted
  #   with_items:
  #     - nfs
  #     - softnas
  #     - monit
    


  - name: login and ack agreement
    #command: "softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd ackagreement"
    shell: |
      softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd ackagreement
    register: softnas_login
  - name: login and ack agreement
    debug:
      var: softnas_login.stdout.split('\n')
      
  - name: login and checkupdate
    #command: "softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd checkupdate"
    shell: |
      softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd checkupdate
    register: softnas_checkupdate
  - name: login and checkupdate
    debug:
      var: softnas_checkupdate.stdout.split('\n')

  - name: login and executeupdate
    #command: "softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd executeupdate"
    shell: |
      softnas-cmd login softnas {{ user_softnas_pw }} && softnas-cmd executeupdate
    register: softnas_executeupdate

  - name: login and executeupdate
    debug:
      var: softnas_executeupdate.stdout.split('\n')
      




  # # - command: "softnas-cmd ackagreement"
  # - command: "softnas-cmd checkupdate"
  # #- command: "softnas-cmd executeupdate"


# [
#   "#cloud-config\n",
#   "hostname: nas1.firehawkvfx.com\n",
#   "fqdn: nas1.firehawkvfx.com\n",
#   "manage_etc_hosts: false\n",
#   "runcmd:\n",
#   "  - echo > /root/.ssh/authorized_keys\n",
#   "  - echo 'export HOSTNAME=nas1.firehawkvfx.com' >> /root/.bash_profile\n",
#   "  - sed -i -e 's/admin@firehawkvfx.com/queglay@gmail.com/g' /var/www/softnas/config/monitoring.ini\n",
#   "  - sed -i -e 's/no/yes/g' /var/www/softnas/config/monitoring.ini\n",
#   "  - sed -i -e 's/SMTP_MAILSERVER=\"\"/SMTP_MAILSERVER=\"smtp-relay.gmail.com\"/g' /var/www/softnas/config/monitoring.ini\n",
#   "  - sed -i -e 's/SMTP_PORT=\"\"/SMTP_PORT=\"587\"/g' /var/www/softnas/config/monitoring.ini\n",
#   "  - sed -i -e 's/SMTP_ENCRYPTION=\"\"/SMTP_ENCRYPTION=\"tlsv1\"/g' /var/www/softnas/config/monitoring.ini\n",
#   "  - cp -a /var/www/softnas/config/general_settings.ini.prototype /var/www/softnas/config/general_settings.ini\n",
#   "  - sed -i -e 's/smtp_mailserver = /smtp_mailserver = \"smtp-relay.gmail.com\"/g' /var/www/softnas/config/general_settings.ini\n",
#   "  - sed -i -e 's/smtp_port = /smtp_port = \"587\"/g' /var/www/softnas/config/general_settings.ini\n",
#   "  - yum install -y nmap\n",
#   "  - nmap -p 80 softnas.com\n",
#   "  - nmap -p 443 softnas.com\n",
#   "  - nmap -p 80 www.softnas.com\n",
#   "  - nmap -p 443 www.softnas.com\n",
#   "  - nmap -p 80 mirror.softnas.com\n",
#   "  - nmap -p 443 mirror.softnas.com\n",
#   "  - sed -i '/MOUNTD_PORT=892/s/^#*//g' /etc/sysconfig/nfs\n",
#   "  - echo '/export *(async,insecure,no_subtree_check,no_root_squash,rw,nohide,fsid=0)' >> /etc/exports\n",
#   "  - echo '/export",
#   {
#     "Ref": "SoftnasExportPath"
#   },
#   " *(async,insecure,no_subtree_check,no_root_squash,rw,nohide)' >> /etc/exports\n",
#   "  - service nfs restart\n",
#   "  - service softnas restart\n",
#   "  - service monit restart\n",
#   "  - /bin/echo > /tmp/updatetype\n",
#   "  - echo '",
#   {
#     "Ref": "SoftnasUserPassword"
#   },
#   "' | passwd --stdin softnas\n",
#   "  - softnas-cmd login softnas ",
#   {
#     "Ref": "SoftnasUserPassword"
#   },
#   "\n",
#   "  - softnas-cmd ackagreement\n",
#   "  - softnas-cmd checkupdate\n",
#   "  - softnas-cmd executeupdate\n"
# ]