- hosts: ansible_control
  remote_user: vagrant
  become: true
  gather_facts: no

# we need different steps for adding a new host in the public subnet, vs private.  we should detect the difference and handle appropriately.

  roles:
  - ssh-add-public-host 