- hosts: ansible_control
  remote_user: deployuser
  become: true
  gather_facts: no

  vars:
    variable_user: deployuser

  roles:
  - ssh-add-public-host

- hosts: firehawkgateway
  remote_user: deployuser
  become: true
  gather_facts: no

  vars:
    variable_user: deployuser

  roles:
  - ssh-add-public-host