### HOUDINI UNIT TEST ###

- hosts: "{{ variable_host | default('role_node_centos') }}"
  remote_user: "{{ variable_connect_as_user | default('centos') }}"
  become: true

  vars_files:
    - /deployuser/ansible/group_vars/all/vars
    - vars.yml
    - /secrets/overrides/ansible/modules/houdini-module/vars.yml

  vars:
    # the become sudo pass is only relevent for local installation if required on the host specified.
    ansible_become_pass: "{{ user_deadlineuser_pw }}"
    
    variable_user: centos
    bastionip: "{{ groups['bastionip'][0] }}"
    
    # whether to execute the unit test.  False will just copy the file.
    execute: true

    # run on boot to test startup latency.
    run_on_boot: false
    
    skip_packages: false
    houdini_install_type: 'node'
    bucket: "{{ installers_bucket }}"
    # the firehawk houdini tools can be linked to a live path on your file system with an variable instead of the default. 
    firehawk_sync_source: '/deployuser/modules/node_centos/modules/openfirehawk-houdini-tools'

  tasks:
  - name: test
    debug:
      msg: 'test a houdini submission to ensure houdini and deadline work'
    tags:
    - always

  - name: s3 sync openfirehawk-houdini-tools push (from local filesystem) and get (from s3 to node) 
    include_role:
      name: houdini-openfirehawk-houdini-tools-sync

  - name: run houdini unit test
    include_role:
      name: houdini-unit-test