---
# tasks file for ansible/roles/validate-encryption
# if the secrets file is not encrypted, then encrypt it.
- name: read the passwd file
  shell: cat /vagrant/secrets/secrets.txt 
  register: check

- name: File is already encrypted
  when: check.stdout.find('ANSIBLE_VAULT') != -1
  debug: msg="Secrets file is already encrypted."

- name: File is not encrypted
  when: check.stdout.find('ANSIBLE_VAULT') == -1
  debug: msg="Secrets file is not encrypted.  Will encrypt"

- name: encrypt
  when: check.stdout.find('ANSIBLE_VAULT') == -1
  shell: |
    cd /vagrant/
    ansible-vault encrypt /vagrant/secrets/secrets.txt
  register: encrypt_shell

- name: encrypt result
  when: check.stdout.find('ANSIBLE_VAULT') == -1
  debug: msg="{{ encrypt_shell.stdout }}"

- name: Validate update
  shell: cat /vagrant/secrets/secrets.txt 
  register: check_post

- name: Validate check
  failed_when: check_post.stdout.find('ANSIBLE_VAULT') == -1
  fail: msg="Warning, wasn't able to encrypt secrets file."