---
# tasks file for ./ansible/roles/pip-centos5

  - name: Add epel repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: "{{ epel_repo_url }}"
      gpgkey: "{{ epel_repo_gpg_key_url }}"
      enabled: yes
    become: true
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
  - name: install pip
    package:
      name: python-pip
      state: latest

  - name: install expect
    package:
      name: expect
      state: present

  - name: uninstall urllib3 because of conflict with rhel 8 packages
    pip:
      name: urllib3
      state: absent
    become: yes

  - name: install python-urllib3 with yum 
    yum:
      name: 'python-urllib3'
      state: present
    become: yes

  - name: install epel-release
    package:
      name: epel-release
      state: present

  - name: install pexpect
    pip:
      name: pexpect
    become: yes
    
  - name: install passlib
    pip:
      name: passlib
    become: yes

  - name: install the package, force upgrade
    package: 
      name: python-boto
    become: true

  - name: install the package, force upgrade
    pip: 
      name: boto3
    become: true