---
# tasks file for ./ansible/roles/pip-centos5
  - name: install pip
    package:
      name: python-pip
      state: latest

  - name: uninstall urllib3 because of conflict with rhel 8 packages
    pip:
      name: urllib3
      state: absent
    become: yes

  - name: install python-urllib3 with yum 
    yum:
      name: 'python-urllib3'
      state: present
    become: yes

  - name: install expect
    package:
      name: expect
      state: present

  - name: install epel-release
    package:
      name: epel-release
      state: present

  - name: install pexpect
    pip:
      name: pexpect
    become: yes
    
  - name: install passlib
    pip:
      name: passlib
    become: yes

  - name: install the package, force upgrade
    package: 
      name: python-boto
    become: true

  - name: install the package, force upgrade
    pip: 
      name: boto3
    become: true