---
# tasks file for ansible/roles/init-keys
- file:
    path: "../keys/"
    state: directory

- stat:
    path: "../keys/{{ key_name }}"
  register: key_test
- name: notify
  debug:
    msg: "A new random key will be generated in ./keys/{{ key_name }}.  It will not be kept in version control, but it will be used to encrypt anything in ./secrets/ which are kept in version control.  It is important you store this key safely because if lost you will not have access to any secrets that define your current infrastructure state."
  when: key_test.stat.exists == false

- name: generate primary password for crypt
  copy:
    content: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"
    dest: "../keys/{{ key_name }}"
  when: key_test.stat.exists == false

- stat:
    path: "../keys/{{ key_name }}"
  register: key_test

- name: make key read only
  file:
    path: "../keys/{{ key_name }}"
    mode: 400
  when: key_test.stat.exists == true