- name: echo bastion public ip
  debug:
    msg: "{{ item }}"
  with_items:
    - "{{ public_ip }}"
    
- file:
    path: "/home/{{ variable_user }}/.ssh/known_hosts"
    state: touch
  become_user: "{{ variable_user }}"
  
- name: clean known hosts
  shell: "ssh-keygen -R {{ public_ip }} -f /home/{{ variable_user }}/.ssh/known_hosts"
  become: true
  become_user: "{{ variable_user }}"

- name: clean known hosts
  shell: "ssh-keygen -R {{ public_address }} -f /home/{{ variable_user }}/.ssh/known_hosts"
  become: true
  become_user: "{{ variable_user }}"

- name: Write the new ec2 instance host key to known hosts
  shell: "ssh-keyscan {{ public_ip }} >> /home/{{ variable_user }}/.ssh/known_hosts"
  become: true
  become_user: "{{ variable_user }}"
    
- name: Write the new ec2 instance host key to known hosts
  shell: "ssh-keyscan {{ public_address }} >> /home/{{ variable_user }}/.ssh/known_hosts"
  become: true
  become_user: "{{ variable_user }}"

- name: define ssh config for bastion if set_bastion=true.
  copy:
    dest: "/home/{{ variable_user }}/.ssh/config"
    mode: '0600'
    owner: "{{ variable_user }}"
    content: |
      Host bastion
        Hostname {{ bastion_address }}
        User centos 
        IdentityFile  {{ cloud_private_key_file }}

      Host "{{ bastion_address }}"
        User centos 
        IdentityFile  {{ cloud_private_key_file }}

      Host "{{ ssh_config_remote_subnet }}"
        User deployuser
        IdentityFile  {{ general_use_ssh_key }}

      Host "10.*.*.*"
        IdentityFile  {{ cloud_private_key_file }}
        User centos
        ProxyCommand ssh -W %h:%p centos@bastion
  become: true
  become_user: "{{ variable_user }}"
  when: set_bastion

- name: define ssh config for bastion if set_bastion=true.
  copy:
    dest: "/home/{{ variable_user }}/.ssh/config"
    mode: '0600'
    owner: "{{ variable_user }}"
    content: |
      Host bastion
        Hostname {{ bastion_address }}
        User centos 
        IdentityFile  {{ cloud_private_key_file }}

      Host "{{ bastion_address }}"
        User centos 
        IdentityFile  {{ cloud_private_key_file }}

      Host vpn
        Hostname {{ vpn_address }}
        User openvpnas 
        IdentityFile  {{ cloud_private_key_file }}

      Host "{{ vpn_address }}"
        User openvpnas
        IdentityFile  {{ cloud_private_key_file }}

      Host "{{ ssh_config_remote_subnet }}"
        User deployuser
        IdentityFile  {{ general_use_ssh_key }}

      Host "10.*.*.*"
        IdentityFile  {{ cloud_private_key_file }}
        User centos
        ProxyCommand ssh -W %h:%p centos@bastion
  become: true
  become_user: "{{ variable_user }}"
  when: set_vpn | bool